In [1]:
import adaboost

In [3]:
datMat, classLabels = adaboost.loadSimpData()

In [4]:
datMat

matrix([[ 1. ,  2.1],
        [ 2. ,  1.1],
        [ 1.3,  1. ],
        [ 1. ,  1. ],
        [ 2. ,  1. ]])

In [5]:
classLabels

[1.0, 1.0, -1.0, -1.0, 1.0]

# dive into buildStump

In [6]:
dataArr = datMat


In [7]:
dataArr

matrix([[ 1. ,  2.1],
        [ 2. ,  1.1],
        [ 1.3,  1. ],
        [ 1. ,  1. ],
        [ 2. ,  1. ]])

In [8]:
from numpy import *

In [9]:
dataMatrix = mat(dataArr)

In [10]:
dataMatrix

matrix([[ 1. ,  2.1],
        [ 2. ,  1.1],
        [ 1.3,  1. ],
        [ 1. ,  1. ],
        [ 2. ,  1. ]])

In [11]:
labelMat = mat(classLabels).T

In [12]:
labelMat

matrix([[ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]])

In [13]:
m,n = shape(dataMatrix)

In [14]:
m

5

In [15]:
n

2

In [16]:
m,n

(5, 2)

In [17]:
numSteps = 10.0; bestStump = {}; bestClasEst = mat(zeros((m,1)))

In [18]:
 minError = inf #init error sum, to +infinity

# dive into adaBoostTrainDS

In [19]:
weakClassArr = []
m = shape(dataArr)[0]

In [20]:
m

5

In [21]:
D = mat(ones((m,1))/m)   #init D to all equal
aggClassEst = mat(zeros((m,1)))

## take the 1st iteration as an example

In [22]:
from adaboost import *
from numpy import *

In [23]:
bestStump,error,classEst = buildStump(dataArr,classLabels,D)#build Stump

In [24]:
bestStump

{'dim': 0, 'ineq': 'lt', 'thresh': 1.3}

In [25]:
error

matrix([[ 0.2]])

In [26]:
classEst

array([[-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.]])

In [27]:
alpha = float(0.5*log((1.0-error)/max(error,1e-16)))#calc alpha, throw in max(error,eps) to account for error=0
bestStump['alpha'] = alpha  
weakClassArr.append(bestStump)      

In [28]:
print "classEst: ",classEst.T

classEst:  [[-1.  1. -1. -1.  1.]]


In [29]:
mat(classLabels).T

matrix([[ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]])

In [30]:
alpha

0.6931471805599453

In [31]:
classEst

array([[-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.]])

In [32]:
expon = multiply(-1*alpha*mat(classLabels).T,classEst) #exponent for D calc, getting messy

In [33]:
expon

matrix([[ 0.69314718],
        [-0.69314718],
        [-0.69314718],
        [-0.69314718],
        [-0.69314718]])

In [34]:
D

matrix([[ 0.2],
        [ 0.2],
        [ 0.2],
        [ 0.2],
        [ 0.2]])

In [35]:
D = multiply(D,exp(expon))                              #Calc New D for next iteration

In [36]:
D

matrix([[ 0.4],
        [ 0.1],
        [ 0.1],
        [ 0.1],
        [ 0.1]])

In [37]:
D = D/D.sum()

In [38]:
D

matrix([[ 0.5  ],
        [ 0.125],
        [ 0.125],
        [ 0.125],
        [ 0.125]])

In [39]:
expon

matrix([[ 0.69314718],
        [-0.69314718],
        [-0.69314718],
        [-0.69314718],
        [-0.69314718]])

In [40]:
#calc training error of all classifiers, if this is 0 quit for loop early (use break)
aggClassEst += alpha*classEst

In [41]:
aggClassEst

matrix([[-0.69314718],
        [ 0.69314718],
        [-0.69314718],
        [-0.69314718],
        [ 0.69314718]])

In [42]:
sign(aggClassEst)

matrix([[-1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]])

In [43]:
mat(classLabels).T

matrix([[ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]])

In [44]:
aggErrors = multiply(sign(aggClassEst) != mat(classLabels).T,ones((m,1)))

In [45]:
aggErrors

matrix([[ 1.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [46]:
errorRate = aggErrors.sum()/m

In [2]:
errorRate

NameError: name 'errorRate' is not defined